### ISSUE TITLE
Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=1][exerciseId=4485]

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [jqueiroz/lojban.io#11]
# Description
If possible, please provide a brief description of what is wrong with this exercise.

This question is confusing.

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=1][exerciseId=4485]
- Exercise payload: {"alternatives":["zdani","ta"],"sentences":[{"text":"ta zdani","lojbanic":true}],"title":"Select the <b>house</b>","type":"single-choice"}
- Attempted solution: {"correctAlternative":"zdani"}
- Attempted solution was classified as correct: no
- Validation payload: {"correct":false,"correctAlternative":"ta"}

**Comment by jqueiroz** [comment]
Thank you for the feedback!

Do you feel that the exercise could be improved simply with a change in the statement?

**Comment by EmergencyTemporalShift** [comment]
I honestly don't know how to format that same question in a way that makes sense.

**Comment by emorchy** [comment]
Is the same exercise? It seems the problem has been resolved.
![ta zdani](https://user-images.githubusercontent.com/40243355/98886471-016c0100-2449-11eb-9d84-77bc4dbb5427.png)

**Comment by jqueiroz** [comment]
The issue raised by EmergencyTemporalShift is that a new student could think that the correct answer is "zdani" instead of "ta".

Pondering more about this, and also taking feedback from IRC, I feel that this mistake, despite not being extremely rare, is not that disruptive to the learning experience either. Students quickly notice that there is a pattern for exercises of the type "Select the house", "Select the x1", etc. So there will be at most a few failed attempts and students will learn. Balancing this against the fact that there is no straightforward to mitigate this (other than completely removing these exercises, which would be highly detrimental), I think this is acceptable for now.

If this later proves to be too disruptive, or if someone has an idea for a fix, we can revisit this issue. I am closing it for now.
