### ISSUE TITLE
Feedback regarding lesson: Abstractions 1

### ISSUE THREAD

**Issue by xoltar** [jqueiroz/lojban.io#81]
It's very difficult to understand the distinction between the different kinds of abstraction made in this lesson. I'm not sure what to suggest, but it's not at all clear which one to pick in each situation (other than for direct quotes, that's clear enough). In general "as an event" and "as a predicate" are not meaningful distinctions to me at this stage. Maybe expand on that?

### Context
For context, this feedback refers to the lesson "Abstractions 1" in the course "Getting started with Lojban (alpha)".

**Comment by jqueiroz** [comment]
Thank you! I really appreciate the feedback.

Based on discussion here and on #ckule, it seems that many other students are having difficulty with this part of the lessons. I will think carefully about how to better explain the distinction between "nu" and "du'u" and then update the lesson accordingly. This might take some time. I will also check if more experienced Lojbanists have suggestions on how to improve this.

Meanwhile, to unblock your studies, I suggest reading about abstractions from the [UnCLL Chapter 11](https://lojban.pw/cll/uncll-1.2.11/xhtml_section_chunks/chapter-abstractions.html).

**Comment by emorchy** [comment]
I too had a similar difficulty regarding abstractions. I would be willing to help in any way I can.

**Comment by jqueiroz** [comment]
Thank you, Ethan! Any help would be appreciated :)

Feel free to propose improvements here or even submit a PR changing the lesson.

**Comment by emorchy** [comment]
Consider the following example:
{mi djuno lo _nu_ gleki lo mlatu} versus {mi djuno lo _du'u_ gleki lo mlatu}
The first example states, "I know the event of me liking cats". That doesn't sound right. Taken from [UnCLL Chapter 11.7](https://lojban.pw/cll/uncll-1.2.11/xhtml_section_chunks/section-predications.html):

> Events are actually or potentially physical, and can't be contained inside one's mind, except for events of thinking, feeling, and the like...

Perhaps it would be beneficial to note that "nu" represents a physical event that can/may occur in real life, and because of this, cannot be restricted to the mind.
Thus, we need another abstraction to make claims about the world that aren't physical. The second part of the example means, "I know the predication that I like cats". Significantly better. Using words like "knowing, believing, learning, seeing, and hearing" restricts an event to the mind and requires {du'u} to represent the abstraction.
Next time, ask yourself, **Does the selbri represent a physical event or a mental event?**
I may be going off on a tangent here, but predication can be split into two separate categories: ontological (where predicates pertain to things) and logical (where predicates are something that is said of things). Hence, ontological predication may be {lo nu}, while logical predication may be {lo du'u}.

**Comment by emorchy** [comment]
If the above comment has helped @xoltar I would love to submit a pull request (assuming my statements are accurate).

**Comment by emorchy** [comment]
After asking #ckule for clarification on the issue, {*nu*} designates a spatio-temporal event; {*du’u*} designates a raw proposition:
### du'u
Unlike my previous conclusion, {*du'u*} represents a "proposition of".
**Proposition:** claim that is either true or false

**Example:** {mi djuno lo du'u do ctuca mi} or "I know that you taught me"
The second place of {djuno} is always a *true proposition* because the knower regards their facts as true. This can be easily explained with:
I | know | the proposition of | you teaching me (is true)
It would make no sense to have {mi djuno lo nu do ctuca mi} because no one can know an event. It is a mess semantically.
### nu
{*nu*} represents an "event of".
**Event:** Something that happens, whether it happens or could happen physically and/or spatially

**Example:** {do nupre lo nu dunda lo mlatu} or "You promised to donate the cat."
Someone promises to do a physical and/or spacial event. This can be explained with:
You | promise | the event of | donating the cat
Of course, you would promise an event instead of a proposition.

**Comment by jqueiroz** [comment]
Thank you!

That sounds great, please feel free to submit a pull request :)

**Comment by emorchy** [comment]
Will do. ETA 5:00 UTC

**Comment by emorchy** [comment]
I just submitted a PR. I can also include flash cards if it is helpful.

**Comment by emorchy** [comment]
@xoltar has [this](#105 ) helped with your understanding of abstractions?

**Comment by vinivosh** [comment]
@emorchy I think the distinction between "nu" and "du'u" is much clearer now, very nice revision.

**Comment by jqueiroz** [comment]
Indeed, the lesson is much clearer now :)

I am closing this issue, but anyone please feel free to open a new open if they believe the lesson is still confusing.

Thanks again @emorchy!
