### ISSUE TITLE
Incorrect exercise: [courseId=grammar-intro_eng][lessonNumber=7][exerciseId=96]

### ISSUE THREAD

**Issue by xoltar** [jqueiroz/lojban.io#92]
# Description
I'm not sure about this one, but isn't my answer correct? Without cu, ma would apply to gerku, not to dunda, right?

# Diagnostics information (do not remove)
- Exercise identifier: [courseId=grammar-intro_eng][lessonNumber=7][exerciseId=96]
- Exercise payload: {"sentences":[{"text":"To whom did you give the dogs?","lojbanic":false}],"title":"Translate without using \"ku\"","type":"typing"}
- Attempted solution: {"text":"do dunda lo gerku cu ma"}
- Attempted solution was classified as correct: no
- Validation payload: {"canonicalAnswer":"do dunda lo gerku ma","correct":false}

**Comment by jqueiroz** [comment]
The "ma" functions as a sumti, so it automatically closes "lo gerku". The sentece "do dunda lo gerku **ma**" parses the same way as "do dunda lo gerku **mi**" (which is equivalent to "do dunda lo gerku ku mi").

If you write terminate "lo gerku" with "ku" instead of "cu", as in "do dunda lo gerku ku ma", The reason that "cu" does not work is that "cu" is not quite a terminator, but rather an initiator for a following selbri. Whenever "cu" appears in a sentence, it marks it forces what follows to be a selbri, and terminates as much as needed for that to happen.
